#' @importFrom evaluate evaluate
#' @importFrom htmltools HTML
#' @importFrom htmltools attachDependencies
#' @importFrom htmltools div
#' @importFrom htmltools htmlDependency
#' @importFrom htmltools tags
#' @importFrom htmlwidgets createWidget
#' @importFrom jsonlite base64_dec
#' @importFrom jsonlite base64_enc
#' @importFrom knitr all_labels
#' @importFrom knitr knit_hooks
#' @importFrom knitr knit_meta_add
#' @importFrom knitr knit_print
#' @importFrom knitr opts_chunk
#' @importFrom knitr opts_hooks
#' @importFrom knitr opts_knit
#' @importFrom knitr spin
#' @importFrom lifecycle deprecated
#' @importFrom markdown markdownExtensions
#' @importFrom markdown markdownToHTML
#' @importFrom promises "%>%"
#' @importFrom promises promise
#' @importFrom promises then
#' @importFrom rlang"%||%"
#' @importFrom rprojroot find_root
#' @importFrom rprojroot is_r_package
#' @importFrom stringr str_trim
#' @importFrom stringr str_remove
#' @importFrom stringr str_split
#' @importFrom shiny invalidateLater
#' @importFrom shiny isolate
#' @importFrom shiny observe
#' @importFrom shiny observeEvent
#' @importFrom shiny reactive
#' @importFrom shiny reactiveValues
#' @importFrom shiny req
#' @importFrom stats runif
#' @importFrom utils getFromNamespace
#' @importFrom utils installed.packages
#' @importFrom utils write.table
#' @importFrom withr with_envvar
#' @importFrom learnr answer
#' @importFrom learnr answer_fn
#' @importFrom learnr available_tutorials
#' @importFrom learnr correct
#' @importFrom learnr disable_all_tags
#' @importFrom learnr duplicate_env
#' @importFrom learnr event_register_handler
#' @importFrom learnr external_evaluator
#' @importFrom learnr filesystem_storage
#' @importFrom learnr finalize_question
#' @importFrom learnr get_tutorial_info
#' @importFrom learnr get_tutorial_state
#' @importFrom learnr incorrect
#' @importFrom learnr initialize_tutorial
#' @importFrom learnr mark_as
#' @importFrom learnr one_time
#' @importFrom learnr question
#' @importFrom learnr question_checkbox
#' @importFrom learnr question_is_correct
#' @importFrom learnr question_is_valid
#' @importFrom learnr question_numeric
#' @importFrom learnr question_radio
#' @importFrom learnr question_text
#' @importFrom learnr question_ui_completed
#' @importFrom learnr question_ui_initialize
#' @importFrom learnr question_ui_try_again
#' @importFrom learnr quiz
#' @importFrom learnr random_encouragement
#' @importFrom learnr random_phrases_add
#' @importFrom learnr random_praise
#' @importFrom learnr run_tutorial
#' @importFrom learnr safe
#' @importFrom learnr safe_env
