jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret
        env:
          secret_email: ${{ secrets.SECRET_EMAIL }}
        run: |
          example-command "$secret_email"
